name: impftermin-check
dependencies:
  - python=3.*
  - pip
  - pip:
      - selenium==3.141.0
      - boto3==1.17.88
      - yapf==0.31.0
      - pylint==2.8.3
      - python-telegram-bot==13.6
      - emoji==1.2.0
